services:
  - type: web
    name: event-management-backend
    env: go
    plan: free
    buildCommand: go build -o main ./cmd/api
    startCommand: ./main
    envVars:
      - key: SERVER_PORT
        value: 3000
      - key: DB_SSLMODE
        value: require
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: event-management-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: event-management-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: event-management-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: event-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: event-management-db
          property: password

databases:
  - name: event-management-db
    databaseName: eventdb
    user: eventuser
    plan: free
